version: "1.0"
projectName: SIQAAutomationProject
runtimes:
- runtimeAlias: APSAERT_30Sep
  assets:
  - name: APSAClientApp
    type: clientapplication
- runtimeAlias: Cloud Runtime
  assets:
  - name: SIQAAutomation
    type: clientapplication
