version: "1.0"
projectName: SIQAAutomationProject
runtimes:
- runtimeAlias: APSAERT_Oct1st
  assets:
  - name: SIQAAutomationProject.project.siqaautomation.WmMQAdapter.com_wm_adapter_wmmqadapter_wmMQAdapter.connections.IBMMQ_1
    type: connection
- runtimeAlias: APSAERTOct06
  assets:
  - name: APSAAutomation
    type: clientapplication
- runtimeAlias: APSAERT_30Sep
  assets:
  - name: APSAClientApp
    type: clientapplication
- runtimeAlias: Cloud Runtime
  assets:
  - name: SIQAAutomation
    type: clientapplication
