version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAAutomationProject
  gitServerName: aparnasabbineniShared
  gitUrl: https://github.com/aparnasabbineni
  gitUsername: aparnasabbineni
  gitBranch: main
services:
- serviceName: project.siqaautomation.integrations:debugLog
  packages:
  - name: SIQAAutomationProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 12.1.0.0.1212
